version: "3.8"

services:
    db:
        image: kartoza/postgis:12.4
        environment: 
            - POSTGRES_DBNAME=postgis
            - POSTGRES_USER=postgis
            - POSTGRES_PASSWORD=postgis
        volumes:
            - "dbdata:/var/lib/postgresql"
    web:
        build: .
        command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python manage.py runserver 0.0.0.0:8000'
        volumes:
            - .:/code
        ports:
            - 8000:8000
        depends_on:
            - db

volumes:
    dbdata: