version: "3.8"

services:
    es:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
        environment:
            - discovery.type=single-node
        ports:
            - 9200:9200
            - 9300:9300
        volumes:
            - "esdata:/usr/share/elasticsearch/data"
    db:
        image: kartoza/postgis:12.4
        environment: 
            - POSTGRES_DBNAME=postgis
            - POSTGRES_USER=postgis
            - POSTGRES_PASSWORD=postgis
        volumes:
            - "dbdata:/var/lib/postgresql"
        ports:
            - 5434:5432
    web:
        build: .
        command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python manage.py runserver 0.0.0.0:8000'
        volumes:
            - .:/code
        ports:
            - 8000:8000
        depends_on:
            - db
            - es

volumes:
    dbdata:
        driver: local
    esdata:
        driver: local