# Generated by Django 3.2.12 on 2022-06-21 07:17

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpoly', django.contrib.gis.db.models.fields.MultiPolygonField(srid=3857)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DataImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('gbif_download_id', models.CharField(blank=True, max_length=255)),
                ('gbif_predicate', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('gbif_id', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Occurrence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gbif_id', models.CharField(max_length=255)),
                ('individual_count', models.IntegerField(default=1)),
                ('date', models.DateField()),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=3857)),
                ('municipality', models.CharField(blank=True, max_length=255)),
                ('coordinates_uncertainty', models.FloatField(blank=True, null=True)),
                ('georeference_remarks', models.TextField(blank=True)),
                ('is_catch', models.BooleanField()),
                ('data_import', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.dataimport')),
                ('source_dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.dataset')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.species')),
            ],
        ),
        migrations.AddIndex(
            model_name='occurrence',
            index=models.Index(fields=['date'], name='dashboard_o_date_aea483_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='occurrence',
            unique_together={('gbif_id', 'data_import')},
        ),
    ]
