# Generated by Django 3.2.12 on 2022-06-20 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataimport',
            name='gbif_predicate',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='contains_catches',
            field=models.BooleanField(default=False),
        ),
    ]
