# Generated by Django 3.1.3 on 2020-12-01 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20201201_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrence',
            name='coordinates_uncertainty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='georeference_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='municipality',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
