# Generated by Django 3.1.3 on 2020-12-01 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20201201_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrence',
            name='coordinates_uncertainty',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
