# Generated by Django 3.2.12 on 2022-06-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_dataset_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='gbif_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='gbif_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='municipality',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='species',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
