# Generated by Django 3.2.16 on 2023-01-23 14:07

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_fishnetsquare"),
    ]

    operations = [
        migrations.CreateModel(
            name="BiodiversityIndicatorSpecies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scientific_name", models.CharField(max_length=255)),
                ("s_kingdom", models.CharField(max_length=255)),
                ("s_class", models.CharField(max_length=255)),
                ("s_order", models.CharField(max_length=255)),
                (
                    "species_group",
                    models.CharField(
                        choices=[
                            ("PL", "Plants"),
                            ("BI", "Birds"),
                            ("OD", "Odonata"),
                            ("OT", "Others"),
                        ],
                        default="OT",
                        max_length=2,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BiodiversityIndicatorObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gbif_id", models.CharField(max_length=255)),
                ("date", models.DateField()),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=3857
                    ),
                ),
                (
                    "species",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="dashboard.biodiversityindicatorspecies",
                    ),
                ),
            ],
        ),
    ]
