# Generated by Django 3.1.3 on 2021-04-01 08:27

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20210114_0832'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataset',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=3857),
        ),
    ]
