# Generated by Django 3.2.6 on 2021-08-16 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20210401_0827'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='occurrence',
            index=models.Index(fields=['date'], name='dashboard_o_date_aea483_idx'),
        ),
    ]
